import {calculate,compareCharts,SIGNS,MOON_TEXT,conversationContext,companionReply} from './astro.js';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];const form=$('#birthForm');let profiles=[],selected=[],current=null,pair=null,activeChartTab='d1',context=null,toastTimer;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const cities=[['Mumbai, India',19.076,72.8777,'Asia/Kolkata'],['New Delhi, India',28.6139,77.209,'Asia/Kolkata'],['Bengaluru, India',12.9716,77.5946,'Asia/Kolkata'],['Chennai, India',13.0827,80.2707,'Asia/Kolkata'],['Kolkata, India',22.5726,88.3639,'Asia/Kolkata'],['Shanghai, China',31.2304,121.4737,'Asia/Shanghai'],['Beijing, China',39.9042,116.4074,'Asia/Shanghai'],['Taipei, Taiwan',25.033,121.5654,'Asia/Taipei'],['Hong Kong',22.3193,114.1694,'Asia/Hong_Kong'],['Singapore',1.3521,103.8198,'Asia/Singapore'],['Tokyo, Japan',35.6762,139.6503,'Asia/Tokyo'],['St. Louis, United States',38.627,-90.1994,'America/Chicago'],['Chicago, United States',41.8781,-87.6298,'America/Chicago'],['New York, United States',40.7128,-74.006,'America/New_York'],['Los Angeles, United States',34.0522,-118.2437,'America/Los_Angeles'],['Denver, United States',39.7392,-104.9903,'America/Denver'],['London, United Kingdom',51.5074,-.1278,'Europe/London'],['Paris, France',48.8566,2.3522,'Europe/Paris'],['Sydney, Australia',-33.8688,151.2093,'Australia/Sydney']];
$('#cities').innerHTML=cities.map(c=>`<option value="${esc(c[0])}"></option>`).join('');const zones=[...new Set(cities.map(c=>c[3]))];form.elements.zone.innerHTML+=[...zones.map(z=>`<option value="${z}">${z.replaceAll('_',' ')}</option>`),'<option value="other">Other time zone…</option>'].join('');
function toast(s){$('#toast').textContent=s;$('#toast').style.display='block';clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').style.display='none',5000)}
function view(v){if(!['chart','profiles','compatibility','messages'].includes(v))v='chart';$$('.view').forEach(e=>e.hidden=e.id!==v+'View');$$('[data-view]').forEach(e=>{e.classList.toggle('active',e.dataset.view===v);if(e.getAttribute('role')==='tab')e.setAttribute('aria-selected',String(e.dataset.view===v))});history.replaceState(null,'','#'+v);return v}
$$('[data-view]').forEach(b=>b.addEventListener('click',e=>{e.preventDefault();view(b.dataset.view)}));view(location.hash.slice(1));
form.elements.city.addEventListener('input',()=>{const c=cities.find(c=>c[0]===form.elements.city.value);if(c){form.elements.lat.value=c[1];form.elements.lon.value=c[2];form.elements.zone.value=c[3];form.elements.offset.value='';zoneChanged()}});
function zoneChanged(){$('#customZoneLabel').hidden=form.elements.zone.value!=='other';form.elements.customZone.required=form.elements.zone.value==='other'}form.elements.zone.addEventListener('change',zoneChanged);
form.elements.unknown.addEventListener('change',()=>{form.elements.time.disabled=form.elements.unknown.checked;form.elements.time.required=!form.elements.unknown.checked});
function profileFromForm(){return {...Object.fromEntries(new FormData(form)),zone:form.elements.zone.value==='other'?form.elements.customZone.value:form.elements.zone.value,unknown:form.elements.unknown.checked};}
function fill(p){form.reset();for(const [k,v] of Object.entries(p)){const el=form.elements[k];if(el&&el.type!=='checkbox')el.value=v??'';}form.elements.unknown.checked=!!p.unknown;form.elements.time.disabled=!!p.unknown;form.elements.time.required=!p.unknown;if(!zones.includes(p.zone)){form.elements.zone.value='other';form.elements.customZone.value=p.zone}zoneChanged();$('#formError').textContent='';}
const examples=[{id:'example-maya',name:'Maya (example)',date:'1997-09-17',time:'08:30',city:'Mumbai, India',lat:19.076,lon:72.8777,zone:'Asia/Kolkata',unknown:false,offset:null},{id:'example-alex',name:'Alex (example)',date:'1990-04-20',time:'08:30',city:'St. Louis, United States',lat:38.627,lon:-90.1994,zone:'America/Chicago',unknown:false,offset:null}];
form.addEventListener('submit',e=>{e.preventDefault();try{current=calculate(profileFromForm());pair=null;context=conversationContext([current]);activeChartTab='d1';renderChart();$('#formError').textContent='';}catch(err){$('#formError').textContent=err.message}});
$('#resetForm').onclick=()=>{form.reset();form.elements.id.value='';form.elements.time.disabled=false;form.elements.time.required=true;zoneChanged();$('#formError').textContent=''};
$('#loadExample').onclick=()=>{fill({...examples[0],id:''});form.requestSubmit()};
const degree=p=>`${Math.floor(p.degree)}° ${String(Math.floor((p.degree%1)*60)).padStart(2,'0')}′`;
function diagram(c,divisional=false){const cells=[[0,0],[1,0],[2,0],[3,0],[3,1],[3,2],[3,3],[2,3],[1,3],[0,3],[0,2],[0,1]];const order=[11,0,1,2,3,4,5,6,7,8,9,10];return `<svg viewBox="0 0 320 320" class="chart-svg" role="img" aria-label="${divisional?'D9 Navamsa':'D1 birth'} chart in a South Indian sign layout"><rect x="1" y="1" width="318" height="318" rx="4" fill="none" stroke="#d9bd8b66"/>${cells.map(([x,y],i)=>{const si=order[i],s=SIGNS[si],bodies=c.planets.filter(p=>(divisional?p.d9:p.sign)===s),asc=c.asc&&(divisional?c.asc.d9:c.asc.sign)===s;return `<g><rect x="${x*80}" y="${y*80}" width="80" height="80" fill="none" stroke="#d9bd8b33"/><text class="signlabel" x="${x*80+8}" y="${y*80+17}">${s.slice(0,3)}${asc?' · Asc':''}</text>${bodies.map((p,j)=>`<text x="${x*80+8+(j%3)*23}" y="${y*80+40+Math.floor(j/3)*16}">${p.name.slice(0,2)}</text>`).join('')}</g>`}).join('')}<text x="160" y="151" text-anchor="middle" style="font-size:25px;font-family:Georgia">${divisional?'D9':'D1'}</text><text x="160" y="175" text-anchor="middle" class="signlabel">${divisional?'NAVAMSA':'RASHI CHART'}</text><text x="160" y="199" text-anchor="middle" class="signlabel">SIDEREAL</text></svg>`}
function renderChart(){const c=current;if(!c)return;const p=c.profile;$('#chartResult').innerHTML=`<div class="result-top"><div><h2>${esc(p.name)}’s sky</h2><p>${esc(p.date)} · ${p.unknown?'Time unknown · noon reference':esc(p.time)} · ${esc(p.city)}</p></div><button class="textbutton" data-action="message">Discuss with Chandra ↗</button></div><div class="pills"><span class="pill">Moon <strong>${c.moon.sign}</strong></span><span class="pill">${c.moon.nakshatra} · Pada ${c.moon.pada}</span><span class="pill">Rising <strong>${c.asc?.sign||'Unknown'}</strong></span></div>${c.uncertainty?`<p class="hint">${c.uncertainty}</p>`:''}<div class="result-tabs" role="tablist" aria-label="Chart results">${[['d1','Birth chart'],['d9','Navamsa D9'],['positions','Positions'],['periods','Life periods']].map(([k,t])=>`<button role="tab" aria-selected="${activeChartTab===k}" class="${activeChartTab===k?'active':''}" data-chart-tab="${k}">${t}</button>`).join('')}</div><div id="chartTabContent" role="tabpanel"></div><p class="method-note">${c.method}. Exploratory calculation; placements near boundaries need verification. Interpretations are symbolic, not scientific predictions. UTC: ${c.utc.replace('.000Z','Z')}.</p>`;
const area=$('#chartTabContent');if(activeChartTab==='positions')area.innerHTML=`<div class="table-wrap"><table><thead><tr><th>BODY</th><th>SIGN</th><th>DEGREE</th><th>NAKSHATRA</th><th>HOUSE</th></tr></thead><tbody>${[...(c.asc?[c.asc]:[]),...c.planets].map(p=>`<tr><td>${p.name}</td><td>${p.sign}</td><td>${degree(p)}</td><td>${p.nakshatra} ${p.pada}</td><td>${p.house??'—'}</td></tr>`).join('')}</tbody></table></div>`;
else if((activeChartTab==='d9'||activeChartTab==='periods')&&p.unknown)area.innerHTML='<div class="empty"><h2>A birth time makes the difference.</h2><p>This view is withheld because the birth time is unknown.</p></div>';
else if(activeChartTab==='periods')area.innerHTML=`<h3>Vimshottari mahadashas</h3><p class="hint">Approximate periods derived from the Moon’s birth nakshatra. A year is treated as 365.25 days.</p>${c.periods.map(d=>`<div class="period ${Date.now()>=Date.parse(d.start)&&Date.now()<Date.parse(d.end)?'current':''}"><span>${d.lord}</span><span>${d.start.slice(0,10)} → ${d.end.slice(0,10)}</span><small>${Date.now()>=Date.parse(d.start)&&Date.now()<Date.parse(d.end)?'CURRENT':''}</small></div>`).join('')}`;
else area.innerHTML=`<div class="chart-grid">${diagram(c,activeChartTab==='d9')}<div class="read-copy"><p class="eyebrow">${activeChartTab==='d9'?'A FINER LENS':'YOUR EMOTIONAL LANDSCAPE'}</p><h3>${activeChartTab==='d9'?'The Navamsa perspective':c.moon.sign+' Moon'}</h3><p>${activeChartTab==='d9'?'D9 divides each zodiac sign into nine parts, offering a traditional secondary view of planetary placements. Small birth-time changes can shift this chart.':MOON_TEXT[SIGNS.indexOf(c.moon.sign)]}</p><small>${activeChartTab==='d9'?'Read alongside the birth chart, rather than as a standalone prediction.':'A prompt for reflection, not a fixed description of who you are.'}</small></div></div>`;
$$('[data-chart-tab]').forEach(b=>b.onclick=()=>{activeChartTab=b.dataset.chartTab;renderChart()});$('[data-action="message"]').onclick=()=>{context=conversationContext([current]);view('messages');addBubble('Chandra',`I have ${current.profile.name}’s chart context. Ask about the Moon sign or try a reflection.`)};}
async function api(path,options={}){const r=await fetch(path,{...options,headers:{'Content-Type':'application/json',...options.headers}});let data;try{data=await r.json()}catch{throw Error('Saved profiles are unavailable in this preview. Please use the published website.')}if(!r.ok)throw Error(data.error||'Please try again.');return data}
async function loadProfiles(){try{const data=await api('/api/profiles');profiles=data.profiles;selected=selected.filter(id=>allProfiles().some(p=>p.id===id));$('#storageStatus').textContent='Private account storage';renderProfiles()}catch(e){$('#storageStatus').textContent=e.message;renderProfiles()}}
$('#refreshProfiles').onclick=loadProfiles;
$('#saveProfile').onclick=async()=>{if(!form.reportValidity())return;const b=$('#saveProfile');b.disabled=true;try{const chart=calculate(profileFromForm());const {profile}=await api('/api/profiles',{method:'POST',body:JSON.stringify(chart.profile)});form.elements.id.value=profile.id;await loadProfiles();toast('Birth profile saved to your private account.')}catch(e){$('#formError').textContent=e.message}finally{b.disabled=false}};
let useExamples=false;const allProfiles=()=>useExamples?[...profiles,...examples]:profiles;
function renderProfiles(){const q=$('#profileSearch').value.toLowerCase(),pq=$('#pairSearch').value.toLowerCase();$('#profileCount').textContent=profiles.length;const rows=profiles.filter(p=>(p.name+' '+p.city).toLowerCase().includes(q));$('#profileList').innerHTML=rows.length?rows.map(p=>`<div class="person-row"><span class="avatar">${esc(p.name[0])}</span><div class="info"><h4>${esc(p.name)}</h4><p>${esc(p.date)} · ${p.unknown?'Time unknown':esc(p.time)} · ${esc(p.city)}</p></div><button data-edit="${esc(p.id)}">Edit</button><button data-delete="${esc(p.id)}">Delete</button></div>`).join(''):`<div class="empty"><span class="empty-symbol">✧</span><h2>${q?'No matching profiles.':'Your constellation starts here.'}</h2><p>${q?'Try a different name or place.':'Create a birth profile and save it to compare later.'}</p></div>`;
const choices=allProfiles().filter(p=>(p.name+' '+p.city).toLowerCase().includes(pq));$('#pairProfiles').innerHTML=choices.length?choices.map(p=>`<label class="person-row"><input type="checkbox" data-person="${esc(p.id)}" ${selected.includes(p.id)?'checked':''} ${selected.length===2&&!selected.includes(p.id)?'disabled':''}><span class="avatar">${esc(p.name[0])}</span><div class="info"><h4>${esc(p.name)}</h4><p>${esc(p.date)} · ${esc(p.city)}</p></div></label>`).join(''):'<p class="hint" style="margin-top:20px">No profiles found. Add a person or try the example pair.</p>';
$('#selectionCount').textContent=selected.length+' / 2';$('#selectedPeople').innerHTML=selected.map(id=>`<button data-remove="${esc(id)}">${esc(allProfiles().find(p=>p.id===id)?.name)} ×</button>`).join('');$('#compare').disabled=selected.length!==2;
$$('[data-edit]').forEach(b=>b.onclick=()=>{fill(profiles.find(p=>p.id===b.dataset.edit));view('chart')});$$('[data-delete]').forEach(b=>b.onclick=async()=>{const p=profiles.find(p=>p.id===b.dataset.delete);if(!confirm(`Delete ${p.name}’s saved birth profile?`))return;try{await api('/api/profiles/'+encodeURIComponent(p.id),{method:'DELETE'});await loadProfiles();toast('Profile deleted.')}catch(e){toast(e.message)}});$$('[data-person]').forEach(b=>b.onchange=()=>{selected=b.checked?[...selected,b.dataset.person]:selected.filter(id=>id!==b.dataset.person);renderProfiles()});$$('[data-remove]').forEach(b=>b.onclick=()=>{selected=selected.filter(id=>id!==b.dataset.remove);renderProfiles()});}
$('#profileSearch').oninput=renderProfiles;$('#pairSearch').oninput=renderProfiles;$('#demoPair').onclick=()=>{useExamples=true;selected=examples.map(p=>p.id);renderProfiles();compareSelected()};
function compareSelected(){try{if(selected.length!==2)throw Error('Choose exactly two different people.');const charts=selected.map(id=>calculate(allProfiles().find(p=>p.id===id)));pair=compareCharts(...charts);context=conversationContext(charts);$('#compatResult').innerHTML=`<div class="panel-label">YOUR SHARED SKY <span class="badge">TWO-CHART COMPARISON</span></div><div class="pair-hero"><span class="empty-symbol">◎</span><h2>${esc(charts[0].profile.name)} &amp; ${esc(charts[1].profile.name)}</h2><p>${charts[0].moon.sign} Moon &nbsp; · &nbsp; ${charts[1].moon.sign} Moon</p></div>${charts.some(c=>c.profile.unknown)?'<p class="error">A birth time is unknown. Moon positions and angular relationships shown here are provisional noon estimates.</p>':''}<div class="comparison">${pair.rows.map(r=>`<article><h4>${r.label}</h4><p>${r.a} & ${r.b}<br>${r.aspect} · ${r.angle.toFixed(1)}° apart${r.aspect!=='No close major aspect'?`<br>Orb ${r.orb.toFixed(1)}°`:''}</p></article>`).join('')}</div><div class="compare-prompt">${pair.question}</div><button class="secondary full" id="discussPair" style="margin-top:20px">Bring this into a conversation ↗</button><p class="method-note">An exploratory synastry view using major angular relationships (8° maximum orb). This is not a traditional Ashtakoota / 36-point assessment or a verdict on your relationship.</p>`;$('#discussPair').onclick=()=>{view('messages');addBubble('Chandra',`I have the chart context for ${charts.map(c=>c.profile.name).join(' and ')}. Let’s explore how you connect.`)};}catch(e){toast(e.message)}}$('#compare').onclick=compareSelected;
function addBubble(who,text){const b=document.createElement('div');b.className='bubble'+(who==='You'?' user':'');const label=document.createElement('small');label.textContent=who.toUpperCase();b.append(label,document.createTextNode(text));$('#chatLog').append(b);$('#chatLog').scrollTop=$('#chatLog').scrollHeight;}
function chat(text){addBubble('You',text);const reply=companionReply(text,context);if(reply.clear)context=null;addBubble('Chandra',reply.text);}
addBubble('Chandra','Hi, I’m Chandra. Calculate a chart or compare two people, then bring your questions here. This is a guided preview; nothing is sent to iMessage.');$('#chatForm').onsubmit=e=>{e.preventDefault();const text=$('#chatInput').value.trim();if(!text)return;chat(text);$('#chatInput').value=''};$$('[data-prompt]').forEach(b=>b.onclick=()=>chat(b.dataset.prompt));
$('#copyContext').onclick=()=>{if(!context){toast('Calculate a chart or compare two profiles first.');return}$('#contextPreview').textContent=JSON.stringify(context,null,2);$('#contextDialog').showModal()};$('#contextDialog .close').onclick=()=>$('#contextDialog').close();$('#confirmCopy').onclick=async()=>{try{const bytes=new TextEncoder().encode(JSON.stringify(context));const payload=btoa(String.fromCharCode(...bytes));await navigator.clipboard.writeText('/chandra import '+payload);toast('Context copied. Paste it into your connected Chandra iMessage chat.');$('#contextDialog').close()}catch{toast('Clipboard access was unavailable. Please allow clipboard access and try again.')}};
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'navigate_chandra_workspace',description:'Open a Chandra workspace section. Does not save profiles or send messages.',inputSchema:{type:'object',properties:{view:{type:'string',enum:['chart','compatibility','profiles','messages']}},required:['view'],additionalProperties:false},annotations:{readOnlyHint:false},execute:input=>{if(!['chart','compatibility','profiles','messages'].includes(input.view))throw Error('Invalid workspace view');return {view:view(input.view)}}})).catch(()=>{})}catch{}}
loadProfiles();
